### ISSUE TITLE
Requirement 2/11/2022

### ISSUE THREAD

**Issue by TutyatornS** [gadgertstory/trusted-by-ggs-fe#1]
- [x] warranty insert/update/delete #2 
- [x] search warranty by user #3 
- [x] design ui warranty #2 #3 

---------------------------------
- แยก microservice โดยทำตัวใหญ่เชื่อมกับ warranty ก่อน
- (microservice-warranty) เริ่มจากหน้า read ของ user ก่อน เพื่อให้เขาค้นหา serial no. ได้ #5 
- (microservice-auth) ย้าย Authentication เป็นอีก microservice #6 
- (microservice-warranty) CRUD warranty #4 
- (microservice-repair) ย้าย Repair System เป็นอีก microservice #7 
- Jenkins

-----------------

- microservice ที่ต้องการข้อมูล(Read)จาก microservice ตัวอื่นที่จัดการข้อมูลนั้นๆ(CRUD) ให้สร้าง function Read ขึ้นมาภายในตัว (สำหรับ Read เท่านั้น)
